### ISSUE TITLE
HTTP request failed when I run servicenow 

### ISSUE THREAD

**Issue by jaishan** [rapid7/nexpose_ticketing#27]
Hi can anyone help me with the following issue.

![image](https://user-images.githubusercontent.com/14957392/34823872-38992c66-f6f2-11e7-8efe-001f952bb939.png)

**Comment by jaishan** [comment]
/usr/local/rvm/gems/ruby-2.4.2/gems/nexpose_ticketing-1.5.2/bin$ ruby nexpose_ticketing servicenow
Still waiting. Current status: Started
/usr/local/rvm/gems/ruby-2.4.2/gems/nexpose_ticketing-1.5.2/lib/nexpose_ticketing/report_helper.rb:39: warning: constant ::TRUE is deprecated
/usr/local/rvm/gems/ruby-2.4.2/gems/nexpose_ticketing-1.5.2/lib/nexpose_ticketing/helpers/servicenow_helper.rb:238:in `block in generate_post_request': HTTP request failed: 302 (RuntimeError)
        from /usr/local/rvm/gems/ruby-2.4.2/gems/typhoeus-1.3.0/lib/typhoeus/request/callbacks.rb:128:in `block in execute_callbacks'
        from /usr/local/rvm/gems/ruby-2.4.2/gems/typhoeus-1.3.0/lib/typhoeus/request/callbacks.rb:127:in `each'
        from /usr/local/rvm/gems/ruby-2.4.2/gems/typhoeus-1.3.0/lib/typhoeus/request/callbacks.rb:127:in `execute_callbacks'
        from /usr/local/rvm/gems/ruby-2.4.2/gems/typhoeus-1.3.0/lib/typhoeus/request/operations.rb:35:in `finish'
        from /usr/local/rvm/gems/ruby-2.4.2/gems/typhoeus-1.3.0/lib/typhoeus/easy_factory.rb:159:in `block in set_callback'
        from /usr/local/rvm/gems/ruby-2.4.2/gems/ethon-0.11.0/lib/ethon/easy/response_callbacks.rb:68:in `block in complete'
        from /usr/local/rvm/gems/ruby-2.4.2/gems/ethon-0.11.0/lib/ethon/easy/response_callbacks.rb:68:in `each'
        from /usr/local/rvm/gems/ruby-2.4.2/gems/ethon-0.11.0/lib/ethon/easy/response_callbacks.rb:68:in `complete'
        from /usr/local/rvm/gems/ruby-2.4.2/gems/ethon-0.11.0/lib/ethon/multi/operations.rb:151:in `check'
        from /usr/local/rvm/gems/ruby-2.4.2/gems/ethon-0.11.0/lib/ethon/multi/operations.rb:164:in `run'
        from /usr/local/rvm/gems/ruby-2.4.2/gems/ethon-0.11.0/lib/ethon/multi/operations.rb:43:in `perform'
        from /usr/local/rvm/gems/ruby-2.4.2/gems/typhoeus-1.3.0/lib/typhoeus/hydra/runnable.rb:15:in `run'
        from /usr/local/rvm/gems/ruby-2.4.2/gems/typhoeus-1.3.0/lib/typhoeus/hydra/memoizable.rb:51:in `run'
        from /usr/local/rvm/gems/ruby-2.4.2/gems/nexpose_ticketing-1.5.2/lib/nexpose_ticketing/helpers/servicenow_helper.rb:131:in `create_tickets'
        from /usr/local/rvm/gems/ruby-2.4.2/gems/nexpose_ticketing-1.5.2/lib/nexpose_ticketing/ticket_service.rb:237:in `ticket_rate_limiter_processor'
        from /usr/local/rvm/gems/ruby-2.4.2/gems/nexpose_ticketing-1.5.2/lib/nexpose_ticketing/ticket_service.rb:288:in `ensure in ticket_rate_limiter'
        from /usr/local/rvm/gems/ruby-2.4.2/gems/nexpose_ticketing-1.5.2/lib/nexpose_ticketing/ticket_service.rb:291:in `ticket_rate_limiter'
        from /usr/local/rvm/gems/ruby-2.4.2/gems/nexpose_ticketing-1.5.2/lib/nexpose_ticketing/ticket_service.rb:216:in `full_new_site_report'
        from /usr/local/rvm/gems/ruby-2.4.2/gems/nexpose_ticketing-1.5.2/lib/nexpose_ticketing/ticket_service.rb:184:in `block in delta_site_report'
        from /usr/local/rvm/gems/ruby-2.4.2/gems/nexpose_ticketing-1.5.2/lib/nexpose_ticketing/ticket_service.rb:178:in `each'
        from /usr/local/rvm/gems/ruby-2.4.2/gems/nexpose_ticketing-1.5.2/lib/nexpose_ticketing/ticket_service.rb:178:in `delta_site_report'
        from /usr/local/rvm/gems/ruby-2.4.2/gems/nexpose_ticketing-1.5.2/lib/nexpose_ticketing/ticket_service.rb:356:in `delta_scan'
        from /usr/local/rvm/gems/ruby-2.4.2/gems/nexpose_ticketing-1.5.2/lib/nexpose_ticketing/ticket_service.rb:312:in `start'
        from /usr/local/rvm/gems/ruby-2.4.2/gems/nexpose_ticketing-1.5.2/lib/nexpose_ticketing.rb:8:in `start'
        from nexpose_ticketing:53:in `<main>'

Anyone facing this issue. why the error or where exactly i have to look

**Comment by jaishan** [comment]
I resolved the issue, this is due to the servicenow portal address we use in the servicenow.config file. Make sure it should have the JSON formatted URL.
